mongo:
  servers:
    -
      name: localhost
      port: 27017
  database: development
  username: salesforceAdmin
  password: iamsalesforce

---

spring:
    profiles: test
mongo:
  servers:
    -
      name:
      port: 27017
  database: test
  username: test
  password: test

---

spring:
    profiles: production

mongo:
  servers:
    -
      name: ${MONGO_SERVICE_SERVERS_0_NAME}
      port: ${MONGO_SERVICE_SERVERS_0_PORT}
    -
      name: ${MONGO_SERVICE_SERVERS_1_NAME}
      port: ${MONGO_SERVICE_SERVERS_1_PORT}
  database: ${MONGO_SERVICE_DATABASE}
  username: ${MONGO_SERVICE_USERNAME}
  password: ${MONGO_SERVICE_PASSWORD}